// @frontal/design-system
// Centralized barrel package that exports all Frontal design system packages

// Export blocks
export { blocks } from "@frontal/blocks";

// Export charts
// Charts package has no exports currently

// Export colors
// Import from the main package and re-export explicitly
import {
	type BlueDarkScale,
	type BlueScale,
	type BrownDarkScale,
	type BrownScale,
	blue,
	blueDark,
	brown,
	brownDark,
	type ColorScale,
	type ColorScaleName,
	type ColorShade,
	type ColorValue,
	type CSSColor,
	type CyanDarkScale,
	type CyanScale,
	cyan,
	cyanDark,
	type ExtendedColorShade,
	type GrayDarkScale,
	type GrayScale,
	type GreenDarkScale,
	type GreenScale,
	getAllScales,
	getColor,
	getScale,
	gray,
	grayDark,
	green,
	greenDark,
	type OKLCHColor,
	type OrangeDarkScale,
	type OrangeScale,
	orange,
	orangeDark,
	type PinkDarkScale,
	type PinkScale,
	type PurpleDarkScale,
	type PurpleScale,
	pink,
	pinkDark,
	purple,
	purpleDark,
	type RedDarkScale,
	type RedScale,
	red,
	redDark,
	type SemanticColors,
	type SemanticDarkColors,
	semantic,
	semanticDark,
	type TealDarkScale,
	type TealScale,
	teal,
	tealDark,
	toCSSVar,
	type YellowDarkScale,
	type YellowScale,
	yellow,
	yellowDark,
} from "@frontal/colors";

export {
	gray,
	grayDark,
	type GrayScale,
	type GrayDarkScale,
	blue,
	blueDark,
	type BlueScale,
	type BlueDarkScale,
	cyan,
	cyanDark,
	type CyanScale,
	type CyanDarkScale,
	yellow,
	yellowDark,
	type YellowScale,
	type YellowDarkScale,
	brown,
	brownDark,
	type BrownScale,
	type BrownDarkScale,
	green,
	greenDark,
	type GreenScale,
	type GreenDarkScale,
	teal,
	tealDark,
	type TealScale,
	type TealDarkScale,
	pink,
	pinkDark,
	type PinkScale,
	type PinkDarkScale,
	purple,
	purpleDark,
	type PurpleScale,
	type PurpleDarkScale,
	orange,
	orangeDark,
	type OrangeScale,
	type OrangeDarkScale,
	red,
	redDark,
	type RedScale,
	type RedDarkScale,
	semantic,
	semanticDark,
	type SemanticColors,
	type SemanticDarkColors,
	type ColorShade,
	type ExtendedColorShade,
	type ColorScaleName,
	type OKLCHColor,
	type CSSColor,
	type ColorValue,
	type ColorScale,
	getColor,
	getScale,
	getAllScales,
	toCSSVar,
};

// Export components
// Components package has no exports currently

// Export icons
// Since icons has 1600+ exports, we import everything and re-export via namespace
// Individual icons can be accessed via Icons.* or imported directly from @frontal/icons
import * as IconsModule from "@frontal/icons";
import {
	extractCategory,
	extractIconName,
	getCategories,
	getIconMetadata,
	getIconProps,
	groupIconsByCategory,
	type IconComponent,
	type IconMetadata,
	type IconProps,
	normalizeColor,
	normalizeSize,
	searchIcons,
} from "@frontal/icons";

// Export icons namespace for accessing all icons
export const Icons = IconsModule;
export type Icons = typeof IconsModule;

// Export icon helpers
export { getIconMetadata, groupIconsByCategory, searchIcons, getCategories };

// Export icon types
export type { IconProps, IconMetadata, IconComponent };

// Export icon utils
export {
	normalizeSize,
	normalizeColor,
	getIconProps,
	extractIconName,
	extractCategory,
};

// Export typeface
export {
	fonts,
	MaisonNeue,
	MaisonNeueMono,
} from "@frontal/typeface";

// Export UI components
export {
	Accordion,
	AccordionContent,
	type AccordionContentProps,
	AccordionItem,
	type AccordionItemProps,
	type AccordionProps,
	AccordionTrigger,
	type AccordionTriggerProps,
	Alert,
	AlertAction,
	type AlertActionProps,
	AlertDescription,
	type AlertDescriptionProps,
	AlertDialog,
	AlertDialogClose,
	type AlertDialogCloseProps,
	AlertDialogContent,
	type AlertDialogContentProps,
	AlertDialogDescription,
	type AlertDialogDescriptionProps,
	AlertDialogFooter,
	type AlertDialogFooterProps,
	AlertDialogHeader,
	type AlertDialogHeaderProps,
	AlertDialogOverlay,
	type AlertDialogOverlayProps,
	AlertDialogPortal,
	AlertDialogTitle,
	type AlertDialogTitleProps,
	AlertDialogTrigger,
	type AlertDialogTriggerProps,
	AlertDialogViewport,
	type AlertDialogViewportProps,
	type AlertProps,
	AlertTitle,
	type AlertTitleProps,
	AnchoredToastProvider,
	AspectRatio,
	type AspectRatioProps,
	Autocomplete,
	AutocompleteClear,
	type AutocompleteClearProps,
	AutocompleteCollection,
	type AutocompleteCollectionProps,
	AutocompleteEmpty,
	type AutocompleteEmptyProps,
	AutocompleteGroup,
	AutocompleteGroupLabel,
	type AutocompleteGroupLabelProps,
	type AutocompleteGroupProps,
	AutocompleteInput,
	type AutocompleteInputProps,
	AutocompleteItem,
	type AutocompleteItemProps,
	AutocompleteList,
	type AutocompleteListProps,
	AutocompletePopup,
	type AutocompletePopupProps,
	AutocompleteRow,
	type AutocompleteRowProps,
	AutocompleteSeparator,
	type AutocompleteSeparatorProps,
	AutocompleteStatus,
	type AutocompleteStatusProps,
	AutocompleteTrigger,
	type AutocompleteTriggerProps,
	AutocompleteValue,
	type AutocompleteValueProps,
	Avatar,
	AvatarFallback,
	type AvatarFallbackProps,
	AvatarImage,
	type AvatarImageProps,
	type AvatarProps,
	anchoredToastManager,
	Badge,
	type BadgeProps,
	Banner,
	BannerAction,
	type BannerActionProps,
	BannerDescription,
	type BannerDescriptionProps,
	type BannerProps,
	BannerTitle,
	type BannerTitleProps,
	Blockquote,
	type BlockquoteProps,
	Box,
	type BoxProps,
	Breadcrumb,
	BreadcrumbEllipsis,
	type BreadcrumbEllipsisProps,
	BreadcrumbItem,
	type BreadcrumbItemProps,
	BreadcrumbLink,
	type BreadcrumbLinkProps,
	BreadcrumbList,
	type BreadcrumbListProps,
	BreadcrumbPage,
	type BreadcrumbPageProps,
	type BreadcrumbProps,
	BreadcrumbSeparator,
	type BreadcrumbSeparatorProps,
	Button,
	ButtonGroup,
	ButtonGroupSeparator,
	ButtonGroupText,
	type ButtonProps,
	badgeVariants,
	boxVariants,
	buttonVariants,
	Calendar,
	type CalendarProps,
	Card,
	CardAction,
	type CardActionProps,
	CardContent,
	CardDescription,
	type CardDescriptionProps,
	CardFooter,
	type CardFooterProps,
	CardHeader,
	type CardHeaderProps,
	CardPanel,
	type CardPanelProps,
	type CardProps,
	CardTitle,
	type CardTitleProps,
	type ChartConfig,
	ChartContainer,
	ChartLegend,
	ChartLegendContent,
	ChartStyle,
	ChartTooltip,
	ChartTooltipContent,
	Checkbox,
	CheckboxGroup,
	type CheckboxGroupProps,
	type CheckboxProps,
	CodeBlock,
	type CodeBlockProps,
	Collapsible,
	CollapsibleContent,
	CollapsiblePanel,
	type CollapsiblePanelProps,
	type CollapsibleProps,
	CollapsibleTrigger,
	type CollapsibleTriggerProps,
	Combobox,
	ComboboxChip,
	type ComboboxChipProps,
	type ComboboxChipRemoveProps,
	ComboboxChips,
	type ComboboxChipsProps,
	ComboboxClear,
	type ComboboxClearProps,
	ComboboxCollection,
	type ComboboxCollectionProps,
	ComboboxEmpty,
	type ComboboxEmptyProps,
	ComboboxGroup,
	ComboboxGroupLabel,
	type ComboboxGroupLabelProps,
	type ComboboxGroupProps,
	ComboboxInput,
	type ComboboxInputProps,
	ComboboxItem,
	type ComboboxItemProps,
	ComboboxList,
	type ComboboxListProps,
	ComboboxPopup,
	type ComboboxPopupProps,
	ComboboxRow,
	type ComboboxRowProps,
	ComboboxSeparator,
	type ComboboxSeparatorProps,
	ComboboxStatus,
	type ComboboxStatusProps,
	ComboboxTrigger,
	type ComboboxTriggerProps,
	ComboboxValue,
	type ComboboxValueProps,
	CommandMenu,
	CommandMenuCollection,
	type CommandMenuCollectionProps,
	CommandMenuDialog,
	type CommandMenuDialogBackdropProps,
	CommandMenuDialogPopup,
	type CommandMenuDialogPopupProps,
	CommandMenuDialogTrigger,
	type CommandMenuDialogTriggerProps,
	type CommandMenuDialogViewportProps,
	CommandMenuEmpty,
	type CommandMenuEmptyProps,
	CommandMenuFooter,
	type CommandMenuFooterProps,
	CommandMenuGroup,
	CommandMenuGroupLabel,
	type CommandMenuGroupLabelProps,
	type CommandMenuGroupProps,
	CommandMenuInput,
	type CommandMenuInputProps,
	CommandMenuItem,
	type CommandMenuItemProps,
	CommandMenuList,
	type CommandMenuListProps,
	CommandMenuPanel,
	type CommandMenuPanelProps,
	type CommandMenuProps,
	CommandMenuSeparator,
	type CommandMenuSeparatorProps,
	CommandMenuShortcut,
	type CommandMenuShortcutProps,
	Container,
	type ContainerProps,
	cn,
	codeBlockVariants,
	containerVariants,
	DatePicker,
	type DatePickerProps,
	DateRangePicker,
	type DateRangePickerProps,
	DateTimePicker,
	type DateTimePickerProps,
	Dialog,
	DialogBackdrop,
	type DialogBackdropProps,
	DialogClose,
	type DialogCloseProps,
	DialogContent,
	DialogDescription,
	type DialogDescriptionProps,
	DialogFooter,
	type DialogFooterProps,
	DialogHeader,
	type DialogHeaderProps,
	DialogOverlay,
	DialogPanel,
	type DialogPanelProps,
	DialogPopup,
	type DialogPopupProps,
	DialogPortal,
	DialogTitle,
	type DialogTitleProps,
	DialogTrigger,
	type DialogTriggerProps,
	DialogViewport,
	type DialogViewportProps,
	Drawer,
	DrawerClose,
	type DrawerCloseProps,
	DrawerContent,
	type DrawerContentProps,
	DrawerDescription,
	type DrawerDescriptionProps,
	DrawerFooter,
	type DrawerFooterProps,
	DrawerHeader,
	type DrawerHeaderProps,
	DrawerOverlay,
	DrawerPortal,
	type DrawerPortalProps,
	type DrawerProps,
	DrawerTitle,
	type DrawerTitleProps,
	DrawerTrigger,
	type DrawerTriggerProps,
	DropdownMenu,
	DropdownMenuCheckboxItem,
	type DropdownMenuCheckboxItemProps,
	DropdownMenuContent,
	type DropdownMenuContentProps,
	DropdownMenuGroup,
	type DropdownMenuGroupProps,
	DropdownMenuItem,
	type DropdownMenuItemProps,
	DropdownMenuLabel,
	type DropdownMenuLabelProps,
	DropdownMenuPortal,
	DropdownMenuRadioGroup,
	type DropdownMenuRadioGroupProps,
	DropdownMenuRadioItem,
	type DropdownMenuRadioItemProps,
	DropdownMenuSeparator,
	type DropdownMenuSeparatorProps,
	DropdownMenuShortcut,
	type DropdownMenuShortcutProps,
	DropdownMenuSub,
	DropdownMenuSubContent,
	type DropdownMenuSubContentProps,
	type DropdownMenuSubProps,
	DropdownMenuSubTrigger,
	type DropdownMenuSubTriggerProps,
	DropdownMenuTrigger,
	type DropdownMenuTriggerProps,
	Empty,
	EmptyContent,
	type EmptyContentProps,
	EmptyDescription,
	type EmptyDescriptionProps,
	EmptyHeader,
	type EmptyHeaderProps,
	EmptyMedia,
	type EmptyMediaProps,
	type EmptyProps,
	EmptyTitle,
	type EmptyTitleProps,
	Field,
	FieldControl,
	FieldDescription,
	type FieldDescriptionProps,
	FieldError,
	type FieldErrorProps,
	FieldLabel,
	type FieldLabelProps,
	type FieldProps,
	Fieldset,
	FieldsetLegend,
	type FieldsetLegendProps,
	type FieldsetProps,
	FieldValidity,
	Flex,
	type FlexProps,
	Form,
	FormControl,
	FormDescription,
	type FormDescriptionProps,
	FormField,
	type FormFieldProps,
	FormItem,
	type FormItemProps,
	FormLabel,
	type FormLabelProps,
	FormMessage,
	type FormMessageProps,
	type FormProps,
	FormProvider,
	Frame,
	FrameDescription,
	type FrameDescriptionProps,
	FrameFooter,
	type FrameFooterProps,
	FrameHeader,
	type FrameHeaderProps,
	FramePanel,
	type FramePanelProps,
	type FrameProps,
	FrameTitle,
	type FrameTitleProps,
	flexVariants,
	Grid,
	GridItem,
	type GridItemProps,
	type GridProps,
	Group,
	type GroupProps,
	GroupSeparator,
	type GroupSeparatorProps,
	GroupText,
	type GroupTextProps,
	gridVariants,
	groupVariants,
	Heading,
	type HeadingProps,
	HoverCard,
	HoverCardContent,
	HoverCardTrigger,
	Image,
	ImageCropper,
	type ImageCropperProps,
	type ImageProps,
	InlineCode,
	type InlineCodeProps,
	Input,
	InputGroup,
	InputGroupAddon,
	type InputGroupAddonProps,
	InputGroupInput,
	type InputGroupInputProps,
	type InputGroupProps,
	InputGroupText,
	InputGroupTextarea,
	type InputGroupTextareaProps,
	type InputGroupTextProps,
	InputKeyboard,
	InputKeyboardGroup,
	type InputKeyboardGroupProps,
	type InputKeyboardProps,
	InputOTP,
	InputOTPGroup,
	InputOTPSeparator,
	InputOTPSlot,
	type InputProps,
	InputUpload,
	type InputUploadProps,
	Item,
	ItemActions,
	type ItemActionsProps,
	ItemContent,
	type ItemContentProps,
	ItemDescription,
	type ItemDescriptionProps,
	ItemFooter,
	type ItemFooterProps,
	ItemGroup,
	type ItemGroupProps,
	ItemHeader,
	type ItemHeaderProps,
	ItemMedia,
	type ItemMediaProps,
	type ItemProps,
	ItemSeparator,
	type ItemSeparatorProps,
	ItemTitle,
	type ItemTitleProps,
	Kbd,
	KbdGroup,
	type KbdGroupProps,
	type KbdProps,
	Label,
	type LabelProps,
	Link,
	type LinkProps,
	List,
	ListItem,
	ListItemAction,
	ListItemActionIcon,
	type ListItemActionIconProps,
	type ListItemActionProps,
	ListItemIcon,
	type ListItemIconProps,
	type ListItemProps,
	ListItemSecondaryAction,
	type ListItemSecondaryActionProps,
	ListItemText,
	type ListItemTextProps,
	type ListProps,
	Menu,
	MenuCheckboxItem,
	type MenuCheckboxItemProps,
	MenuGroup,
	MenuGroupLabel,
	type MenuGroupLabelProps,
	type MenuGroupProps,
	MenuItem,
	type MenuItemProps,
	MenuPopup,
	type MenuPopupProps,
	MenuPortal,
	MenuRadioGroup,
	type MenuRadioGroupProps,
	MenuRadioItem,
	type MenuRadioItemProps,
	MenuSeparator,
	type MenuSeparatorProps,
	MenuShortcut,
	type MenuShortcutProps,
	MenuSub,
	MenuSubPopup,
	type MenuSubPopupProps,
	type MenuSubProps,
	MenuSubTrigger,
	type MenuSubTriggerProps,
	MenuTrigger,
	type MenuTriggerProps,
	Meter,
	MeterIndicator,
	type MeterIndicatorProps,
	MeterLabel,
	type MeterLabelProps,
	type MeterProps,
	MeterTrack,
	type MeterTrackProps,
	MeterValue,
	type MeterValueProps,
	Note,
	NoteContent,
	type NoteContentProps,
	NoteLabel,
	type NoteLabelProps,
	type NoteProps,
	NumberField,
	NumberFieldDecrement,
	type NumberFieldDecrementProps,
	NumberFieldGroup,
	type NumberFieldGroupProps,
	NumberFieldIncrement,
	type NumberFieldIncrementProps,
	NumberFieldInput,
	type NumberFieldInputProps,
	type NumberFieldProps,
	NumberFieldScrubArea,
	type NumberFieldScrubAreaProps,
	noteVariants,
	Pagination,
	PaginationContent,
	type PaginationContentProps,
	PaginationEllipsis,
	type PaginationEllipsisProps,
	PaginationItem,
	type PaginationItemProps,
	PaginationLink,
	type PaginationLinkProps,
	PaginationNext,
	type PaginationNextProps,
	PaginationPrevious,
	type PaginationPreviousProps,
	type PaginationProps,
	Popover,
	PopoverClose,
	type PopoverCloseProps,
	PopoverContent,
	type PopoverContentProps,
	PopoverCreateHandle,
	PopoverDescription,
	type PopoverDescriptionProps,
	PopoverTitle,
	type PopoverTitleProps,
	PopoverTrigger,
	type PopoverTriggerProps,
	PreviewCard,
	PreviewCardContent,
	type PreviewCardContentProps,
	PreviewCardTrigger,
	type PreviewCardTriggerProps,
	Progress,
	ProgressIndicator,
	type ProgressIndicatorProps,
	ProgressLabel,
	type ProgressLabelProps,
	type ProgressProps,
	ProgressTrack,
	type ProgressTrackProps,
	ProgressValue,
	type ProgressValueProps,
	Radio,
	RadioGroup,
	RadioGroupItem,
	type RadioGroupProps,
	type RadioProps,
	ResizableHandle,
	type ResizableHandleProps,
	ResizablePanel,
	ResizablePanelGroup,
	type ResizablePanelGroupProps,
	type ResizablePanelProps,
	ScrollArea,
	type ScrollAreaProps,
	ScrollBar,
	type ScrollBarProps,
	Section,
	type SectionProps,
	Select,
	SelectContent,
	SelectGroup,
	SelectGroupLabel,
	type SelectGroupLabelProps,
	type SelectGroupProps,
	SelectItem,
	type SelectItemProps,
	SelectPopup,
	type SelectPopupProps,
	SelectSeparator,
	type SelectSeparatorProps,
	SelectTrigger,
	type SelectTriggerProps,
	SelectValue,
	type SelectValueProps,
	Separator,
	type SeparatorProps,
	Sheet,
	SheetBackdrop,
	type SheetBackdropProps,
	SheetClose,
	type SheetCloseProps,
	SheetContent,
	SheetDescription,
	type SheetDescriptionProps,
	SheetFooter,
	type SheetFooterProps,
	SheetHeader,
	type SheetHeaderProps,
	SheetOverlay,
	SheetPanel,
	type SheetPanelProps,
	SheetPopup,
	type SheetPopupProps,
	SheetPortal,
	SheetTitle,
	type SheetTitleProps,
	SheetTrigger,
	type SheetTriggerProps,
	type SheetViewportProps,
	Sidebar,
	SidebarContent,
	type SidebarContentProps,
	SidebarFooter,
	type SidebarFooterProps,
	SidebarGroup,
	SidebarGroupAction,
	type SidebarGroupActionProps,
	SidebarGroupContent,
	type SidebarGroupContentProps,
	SidebarGroupLabel,
	type SidebarGroupLabelProps,
	type SidebarGroupProps,
	SidebarHeader,
	type SidebarHeaderProps,
	SidebarInput,
	type SidebarInputProps,
	SidebarInset,
	type SidebarInsetProps,
	SidebarMenu,
	SidebarMenuAction,
	type SidebarMenuActionProps,
	SidebarMenuBadge,
	type SidebarMenuBadgeProps,
	SidebarMenuButton,
	type SidebarMenuButtonProps,
	SidebarMenuItem,
	type SidebarMenuItemProps,
	type SidebarMenuProps,
	SidebarMenuSkeleton,
	type SidebarMenuSkeletonProps,
	SidebarMenuSub,
	SidebarMenuSubButton,
	type SidebarMenuSubButtonProps,
	SidebarMenuSubItem,
	type SidebarMenuSubItemProps,
	type SidebarMenuSubProps,
	type SidebarProps,
	SidebarProvider,
	type SidebarProviderProps,
	SidebarRail,
	type SidebarRailProps,
	SidebarSeparator,
	type SidebarSeparatorProps,
	SidebarTrigger,
	type SidebarTriggerProps,
	Skeleton,
	type SkeletonProps,
	Slider,
	type SliderProps,
	SliderValue,
	type SliderValueProps,
	Snippet,
	type SnippetProps,
	Spinner,
	type SpinnerProps,
	SplitButton,
	type SplitButtonProps,
	Stack,
	type StackProps,
	StepConnector,
	type StepConnectorProps,
	StepContent,
	type StepContentProps,
	StepDescription,
	type StepDescriptionProps,
	StepIndicator,
	type StepIndicatorProps,
	StepItem,
	type StepItemProps,
	Steps,
	type StepsProps,
	StepTitle,
	type StepTitleProps,
	Switch,
	type SwitchProps,
	sectionVariants,
	snippetBlockVariants,
	snippetVariants,
	stackVariants,
	Table,
	TableBody,
	type TableBodyProps,
	TableCaption,
	type TableCaptionProps,
	TableCell,
	type TableCellProps,
	TableFooter,
	type TableFooterProps,
	TableHead,
	TableHeader,
	type TableHeaderProps,
	type TableHeadProps,
	type TableProps,
	TableRow,
	type TableRowProps,
	Tabs,
	TabsContent,
	TabsList,
	type TabsListProps,
	TabsPanel,
	type TabsPanelProps,
	type TabsProps,
	TabsTab,
	type TabsTabProps,
	TabsTrigger,
	Text,
	Textarea,
	type TextareaProps,
	type TextProps,
	TimePicker,
	type TimePickerProps,
	type ToastPosition,
	ToastProvider,
	type ToastProviderProps,
	Toggle,
	ToggleGroup,
	ToggleGroupItem,
	type ToggleGroupProps,
	ToggleGroupSeparator,
	type ToggleGroupSeparatorProps,
	type ToggleGroupToggleProps,
	type ToggleProps,
	Toolbar,
	ToolbarButton,
	type ToolbarButtonProps,
	ToolbarGroup,
	type ToolbarGroupProps,
	ToolbarInput,
	type ToolbarInputProps,
	ToolbarLink,
	type ToolbarLinkProps,
	type ToolbarProps,
	ToolbarSeparator,
	type ToolbarSeparatorProps,
	Tooltip,
	TooltipContent,
	TooltipCreateHandle,
	TooltipPopup,
	type TooltipPopupProps,
	TooltipProvider,
	TooltipTrigger,
	type TooltipTriggerProps,
	toastManager,
	toggleVariants,
	useFormContext,
	useSidebar,
	Video,
	type VideoProps,
} from "@frontal/ui";
