import { exec } from 'node:child_process';
import { existsSync, promises as fs } from 'node:fs';
import path from 'node:path';
import { rimraf } from 'rimraf';
import type { RegistryItem } from '../src/lib/schema';
import { registry } from '../src/registry/index';

type RegistryFile = NonNullable<RegistryItem['files']>[0];

async function buildRegistryIndex() {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`;
  for (const item of registry.items) {
    const resolveFiles = item.files?.map(
      (file: RegistryFile) => `src/components/${file.path}`,
    );
    if (!resolveFiles) {
      continue;
    }

    const componentPath = item.files?.[0]?.path
      ? `@frontal/design-system/${item.files[0].path.replace(/\.(tsx?|jsx?)$/, '')}`
      : '';

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ''}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
		files: [${item.files?.map((file: RegistryFile) => {
      const filePath = `src/${typeof file === 'string' ? file : file.path}`;
      const resolvedFilePath = path.resolve(filePath);
      return typeof file === 'string'
        ? `"${resolvedFilePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ''}"
    }`;
    })}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })`
        : 'null'
    },
    categories: ${JSON.stringify(item.categories)},
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  index += `
  }`;

  console.log(`#️⃣  ${Object.keys(registry.items).length} items found`);

  // Write style index.
  rimraf.sync(path.join(process.cwd(), 'src/registry/__index__.tsx'));
  await fs.writeFile(
    path.join(process.cwd(), 'src/registry/__index__.tsx'),
    index,
  );
}

async function buildRegistryJsonFile() {
  // 1. Fix the path for registry items.
  const fixedRegistry = {
    ...registry,
    items: registry.items.map((item: RegistryItem) => {
      const files = item.files?.map((file: RegistryFile) => {
        return {
          ...file,
          path: `src/components/${file.path}`,
        };
      });

      return {
        ...item,
        files,
      };
    }),
  };

  // 2. Write the content of the registry to `registry.json`
  rimraf.sync(path.join(process.cwd(), 'registry.json'));
  await fs.writeFile(
    path.join(process.cwd(), 'registry.json'),
    JSON.stringify(fixedRegistry, null, 2),
  );

  // 3. Format the registry.json file.
  await exec('prettier --write registry.json');

  // 3. Copy the registry.json to the www/public/r/styles/components directory.
  await fs.cp(
    path.join(process.cwd(), 'registry.json'),
    path.join(process.cwd(), '../www/public/r/styles/components/registry.json'),
    { recursive: true },
  );
}

async function buildRegistry() {
  return new Promise((resolve, reject) => {
    // Use local shadcn copy.
    const process = exec(
      'node ../../packages/shadcn/dist/index.js build registry.json --output ../www/public/r/styles/components',
    );

    // exec(
    //   `pnpm dlx shadcn build registry.json --output ../www/public/r/styles/components`
    // )

    process.on('exit', (code) => {
      if (code === 0) {
        resolve(undefined);
      } else {
        reject(new Error(`Process exited with code ${code}`));
      }
    });
  });
}

async function syncRegistry() {
  // Store the current registry content
  const registryDir = path.join(process.cwd(), 'registry');
  const registryIndexPath = path.join(registryDir, '__index__.tsx');
  let registryContent = null;

  try {
    registryContent = await fs.readFile(registryIndexPath, 'utf8');
  } catch {
    // File might not exist yet, that's ok
  }

  // 0. Copy registries.json from v4 to www before building www registry.
  const v4RegistriesPath = path.join(process.cwd(), 'public/r/registries.json');
  const wwwRegistriesPath = path.resolve(
    process.cwd(),
    '../www/public/r/registries.json',
  );

  if (existsSync(v4RegistriesPath)) {
    // Ensure the www/public/r directory exists.
    await fs.mkdir(path.dirname(wwwRegistriesPath), { recursive: true });
    // Copy registries.json to www.
    await fs.cp(v4RegistriesPath, wwwRegistriesPath);
  }

  // 1. Call pnpm registry:build for www.
  await exec('pnpm --filter=www registry:build');

  // 2. Copy the www/public/r directory to v4/public/r.
  rimraf.sync(path.join(process.cwd(), 'public/r'));
  await fs.cp(
    path.resolve(process.cwd(), '../www/public/r'),
    path.resolve(process.cwd(), 'public/r'),
    { recursive: true },
  );

  // 3. Restore the registry content if we had it
  if (registryContent) {
    await fs.writeFile(registryIndexPath, registryContent, 'utf8');
  }
}

async function buildBlocksIndex() {
  // Get blocks directly from registry instead of importing from __index__ to avoid circular dependency
  const blocks = registry.items.filter(
    (item: RegistryItem) =>
      item.type === 'registry:block' && !item.name.startsWith('chart-'),
  );

  const payload = blocks.map((block: RegistryItem) => ({
    name: block.name,
    description: block.description,
    categories: block.categories,
  }));

  rimraf.sync(path.join(process.cwd(), 'src/registry/__blocks__.json'));
  await fs.writeFile(
    path.join(process.cwd(), 'src/registry/__blocks__.json'),
    JSON.stringify(payload, null, 2),
  );

  await exec('prettier --write src/registry/__blocks__.json');
}

async function main() {
  try {
    console.log('🗂️ Building registry/__index__.tsx...');
    await buildRegistryIndex();

    console.log('🗂️ Building registry/__blocks__.json...');
    await buildBlocksIndex();

    console.log('💅 Building registry.json...');
    await buildRegistryJsonFile();

    console.log('✅ Core registry files generated successfully!');
    console.log(
      'ℹ️  Note: Additional registry building and syncing steps skipped',
    );
  } catch (error) {
    console.error('❌ Error during build process:', error);
    process.exit(1);
  }
}

main();
